name: CI con pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      
      - name: Instalacion de python 3.12.2
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.2"
          
      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          
      - name: Correr pruebas con pytest
        run: |
          pytest tests/ -v  # Ejecuta todas las pruebas